### ISSUE TITLE
Second try is not displayed in the app

### ISSUE THREAD

**Issue by jeyemwey** [MyGrades/mygrades-app#9]
Hi, today I found out that second tries are not displayed in the app.

Expected behavior: The app shows the latest grade for the subject in the overview and lists all tries in the subject view.

Actual behavior: The app only shows the first/missed try and does not show that you passed the exam at the second try.

Background: The `Technische Hochschule Köln` HIS system lists all exam tries of one course and has the exam date at the far right. From what I can see, the newest exam is listed first; so I assume that the app overwrites the second try when reading the first.

I will look deeper into the issue tomorrow but look forward for your input on the topic.

**Comment by jonastheis** [comment]
Hey, 
I think the behaviour should be as follows: All tries (also unsuccessful) are listed in the app as individual grades and are displayed in the semester where the exam was taken, respectively. 

Possible problems: 

- `examId` is not unique anymore in the data model within the app. That's why we decided to use [a hash of a combination of fields as primary key](https://github.com/MyGrades/mygrades-app/blob/master/app/src/main/java/de/mygrades/database/dao/GradeEntry.java#L405). So if there is a distinct combination of `examId`, `semester`, `name` and `attempt` the grades should also be distinct.
- The line in which the latest result is given, might be different and does not match the `TRANSFORMER_MAPPING_ITERATOR` [XPath expression](https://github.com/MyGrades/mygrades-server/blob/master/database/seeds/universities/THKoeln.php#L41) anymore. So the app filters this entry out. 

If you could provide (anonymised) source code of the webpage with the table of grades I'm sure I can be of more help than just guessing :)

**Comment by jeyemwey** [comment]
To the second problem: Would you please tell me the meaning of `TRANSFORMER_MAPPING_ITERATOR`? Then, I can see whether it will change.

I will publish the Table of Grades, but only after the weekend (I don't have my notebook with me right now).

**Comment by tilmanginzel** [comment]
Hi @jeyemwey,

the XPath expression `TRANSFORMER_MAPPING_ITERATOR` selects all table rows which contain grade entries. The app basically iterates over that result set and converts each row into a grade entry.

Instead of publishing your (anonymised) table of grades, you can also send it to us via mail to hallo@mygrades.de.

Thanks for the help. :)

**Comment by jeyemwey** [comment]
I just looked into the app again and the grade does appear now, sorry for the inconvenience. I guess, it was just a caching problem instead of a parsing problem.
